"""production_schema_v2_measurements_tryon_storytelling

Revision ID: 1481f6e79e5c
Revises: 001
Create Date: 2026-06-05 01:14:06.614734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1481f6e79e5c'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('body_bust', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('body_waist', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('body_hips', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('brand_preferences', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('style_preferences', sa.Text(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('editorial_tags', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('storytelling_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('storytelling_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mood_aesthetic', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('occasion', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cinematic_video_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('angles_images_url', sa.Text(), nullable=True))

    with op.batch_alter_table('tryon_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('garments_list', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('body_bust', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('body_waist', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('body_hips', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('style_preferences')
        batch_op.drop_column('brand_preferences')
        batch_op.drop_column('body_hips')
        batch_op.drop_column('body_waist')
        batch_op.drop_column('body_bust')
        batch_op.drop_column('weight')
        batch_op.drop_column('height')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('angles_images_url')
        batch_op.drop_column('cinematic_video_url')
        batch_op.drop_column('occasion')
        batch_op.drop_column('mood_aesthetic')
        batch_op.drop_column('storytelling_description')
        batch_op.drop_column('storytelling_title')
        batch_op.drop_column('editorial_tags')

    with op.batch_alter_table('tryon_sessions', schema=None) as batch_op:
        batch_op.drop_column('body_hips')
        batch_op.drop_column('body_waist')
        batch_op.drop_column('body_bust')
        batch_op.drop_column('weight')
        batch_op.drop_column('height')
        batch_op.drop_column('avatar')
        batch_op.drop_column('garments_list')

    # ### end Alembic commands ###
