"""multi_boutique_v1

Revision ID: 5b9770ab1bbe
Revises: perf_indexes_v1
Create Date: 2026-06-07 00:20:45.369036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b9770ab1bbe'
down_revision: Union[str, None] = 'perf_indexes_v1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('banner_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('hero_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('hero_subtitle', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('hero_image_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('hero_cta_text', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('story_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('story_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('story_image_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('philosophy_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('philosophy_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('accent_color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('font_family', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('seasonal_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('seasonal_desc', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_brands_slug'), ['slug'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_users_brand_id_brands', 'brands', ['brand_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_brand_id_brands', type_='foreignkey')
        batch_op.drop_column('brand_id')

    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_slug'))
        batch_op.drop_column('seasonal_desc')
        batch_op.drop_column('seasonal_title')
        batch_op.drop_column('font_family')
        batch_op.drop_column('accent_color')
        batch_op.drop_column('philosophy_text')
        batch_op.drop_column('philosophy_title')
        batch_op.drop_column('story_image_url')
        batch_op.drop_column('story_description')
        batch_op.drop_column('story_title')
        batch_op.drop_column('hero_cta_text')
        batch_op.drop_column('hero_image_url')
        batch_op.drop_column('hero_subtitle')
        batch_op.drop_column('hero_title')
        batch_op.drop_column('banner_url')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
